### ISSUE TITLE
Create and use Nemo favicons

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo-doc#6]
The page should include a range of suitable favicons based on the "circled N" logo. It might be necessary to create several versions for different devices and contexts.

**Comment by mmarx** [comment]
Deriving the different favicon versions from the SVG can be done automatically, cf. 
https://github.com/Die-KoMa/die-koma.org/commit/2ff571786698e686029bfc68c85f0507272e55c9#diff-621c0d4e1d798274214c5a1d9218138167506a88dcdace8c2bb980d6fb10b08b
